# Generated by Django 5.1 on 2024-10-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuadro', '0001_initial'),
        ('portada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('num_consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripsion', models.CharField(max_length=250)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('estatus', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portada.portada')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series')),
            ],
        ),
    ]
