# Generated by Django 5.1 on 2024-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='estatus',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='observaciones',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
