# Generated by Django 5.1 on 2024-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_inventario_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='descripsion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='observaciones',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
