# Generated by Django 5.1 on 2025-01-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('cuadro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('ficha', models.CharField(max_length=150)),
                ('area_resguardante', models.CharField(max_length=250)),
                ('area_intervienen', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('soporte_docu', models.CharField(max_length=250)),
                ('topologia', models.CharField(max_length=250)),
                ('catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.catalogo')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.seccion')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series')),
                ('subserie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.subserie')),
            ],
        ),
    ]
