# Generated by Django 5.1 on 2025-01-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
