# Generated by Django 5.1 on 2024-11-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='id_subserie',
            new_name='Subserie',
        ),
    ]
