# Generated by Django 5.1 on 2024-10-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiadocu',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='guiadocu',
            name='serie',
        ),
    ]
