# Generated by Django 5.1 on 2024-10-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id_serie', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('codigo_serie', models.TextField()),
                ('descripcion', models.TextField()),
                ('id_seccion', models.ForeignKey(blank=True, db_column='seccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='SubSerie',
            fields=[
                ('SubSerie', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series')),
            ],
        ),
    ]
