# Generated by Django 5.1 on 2025-01-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.TextField()),
                ('codigo_seccion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.TextField()),
                ('codigo_serie', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('delete', models.BooleanField(default=False)),
                ('id_seccion', models.ForeignKey(blank=True, db_column='id_seccion', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='SubSerie',
            fields=[
                ('id_subserie', models.AutoField(primary_key=True, serialize=False)),
                ('subserie', models.TextField()),
                ('codigo_subserie', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('delete', models.BooleanField(default=False)),
                ('id_serie', models.ForeignKey(blank=True, db_column='id_serie', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuadro.series')),
            ],
        ),
    ]
