# Generated by Django 5.1 on 2025-01-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subserie',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
