# Generated by Django 5.1 on 2024-10-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subserie',
            name='id_subserie',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subserie',
            name='SubSerie',
            field=models.CharField(max_length=150),
        ),
    ]
