# Generated by Django 5.1 on 2024-11-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='id_serie',
        ),
    ]
