# Generated by Django 5.1 on 2024-11-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=50)),
                ('serie_documental', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
