# Generated by Django 5.1 on 2024-11-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadpdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docuento',
            new_name='Documento',
        ),
    ]
