# Generated by Django 5.1 on 2024-12-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='alfresco_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portada',
            name='documento_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portada',
            name='documento_ruta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
